# Enable basic peripherals
CONFIG_I2C=y

# ZMK core
CONFIG_ZMK_KEYBOARD_NAME="Filco TKL Wireless"
CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=n

# Logging (optional)
CONFIG_LOG=y

# IMPORTANT:
# KHÔNG set GPIO_MCP23S17 hoặc MCP23017 ở đây
# Zephyr sẽ tự enable driver thông qua devicetree