name: Build ZMK Firmware

on:
  push:
    paths:
      - 'config/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build firmware
        uses: zmkfirmware/zmk-build-action@v3
        with:
          board: nice_nano_v2
          shield: filco_tkl_wireless